name: First_workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run: echo "Hello world!"
    - name: Print Bye
      run: |
        echo "Thanks foe coming"
        echo "Good bye"
        echo "See you again"
