name: First_workflow

on: push

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest_bdd

      - name: Run Unit Tests with Coverage
        run: pytest --cov=./ --cov-report=xml

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

  static_analysis:
    runs-on: ubuntu-latest
    needs: unit_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  package:
    runs-on: ubuntu-latest
    needs: static_analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP Package
        run: |
          echo "Creating source zip package..."
          mkdir package
          zip -r package/source_code.zip . -x "*.git*" "*.github/*" "*.pytest_cache/*"
          ls package/

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-code-package
          path: package/source_code.zip

  Deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Package Artifact
        uses: actions/download-artifact@v4
        with:
          name: source-code-package
          path: ./dist

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Configure Databricks CLI
        run: |
          databricks configure --token <<EOF
          ${{ secrets.DATABRICKS_HOST }}
          ${{ secrets.DATABRICKS_TOKEN }}
          EOF

      - name: Deploy to Databricks Workspace
        run: |
          echo "Unzipping package..."
          unzip ./dist/source_code.zip -d ./dist/unpacked

          echo "Uploading to /Workspace/Shared/src/"
          databricks workspace import_dir ./dist/unpacked /Workspace/Shared/src --overwrite
