name: First_workflow

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # Match your local version or choose LTS (3.11/3.12)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      # Step 4: Run Unit Tests with Coverage
      - name: Unit Testing
        run: pytest --cov=src --cov-report=xml  # Generates coverage.xml in project root

      # Step 5: Upload Coverage XML Report
      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml  # Upload just the XML file
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Step 6: Print Bye
      - name: Print Bye
        run: |
          echo "Thanks for coming"
          echo "Good bye"
          echo "See you again"
