name: First_workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # Match your local version or choose LTS (3.11/3.12)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      # Step 4: Run Unit Tests with Coverage
      - name: Unit Testing
        run: pytest --cov=src --cov-report=xml --cov-report=html

      # Step 5: Print Bye
      - name: Print Bye
        run: |
          echo "Thanks for coming"
          echo "Good bye"
          echo "See you again"